Adding builder for VerifiableCredential
TBD54566975/web5-js pull request #125
Opened 2023-06-13 20:24 UTC by nitro-neal

Added VerifiableCredential builder along with unit tests.

The default constructor sets only things that are not optional:
```
    this.verifiableCredential = {
      '@context'        : contexts as ['https://www.w3.org/2018/credentials/v1', ...string[]],
      credentialSubject : credentialSubject,
      issuer            : issuer,
      type              : types,
      issuanceDate      : getCurrentTimestamp(),
    };
```

Added the builder pattern for the rest of the fields with simple validation
Added unit tests
<img width="492" alt="image" src="https://github.com/TBD54566975/web5-js/assets/5314059/f192c147-bf83-42ea-9c3a-1a627e5be850">

2023-06-14 13:46 UTC, frankhinek requested changes
Awesome to see this contribution @nitro-neal !

Looking forward to many more as you help us build out VC capabilities.

2023-06-14 14:01 UTC, frankhinek commented
@mistermoe When reviewing this PR, I spotted a few things or had a few questions that I should have probably raised in the initial PR.  I didn't notice them until going through a more thorough review today:

### 1. `VerifiableCredential` type definition - `@context`

Including a static string in the type definition:
https://github.com/TBD54566975/web5-js/blob/d1e2d1003a46542e7c06bfd90156a830933eeef0/packages/credentials/src/types.ts#L5-L7

results in awkward type issues in the code, for example:
https://github.com/TBD54566975/web5-js/blob/f78af053f6775b335bd58cd05d4fe25e76b16736/packages/credentials/src/verifiable-credential-builder.ts#L26-L28

Proposal is to define `@context` as its own type and then reference in the `VerifiableCredential` type:

```typescript
/**
 * The data type for `@context` properties of credentials, presentations, etc.
 *
 * @see {@link https://www.w3.org/TR/vc-data-model/#contexts | Credential Contexts}
 */
export type CredentialContext = string | Record<string, any> | (string | Record<string, any>)[]

/**
 * @see {@link https://www.w3.org/TR/vc-data-model/#credentials | VC data model}
 */
export type VerifiableCredential = {
  /** @see {@link CredentialContext} */
  '@context': CredentialContext;
  credentialSubject: CredentialSubject | CredentialSubject[];
...
  ```

Neil is already including the mandatory `'https://www.w3.org/2018/credentials/v1'` value when a new credential is created, and this seems like a better trade-off to the intellisense code completion resulting from including the string in the type def, since its not likely developers are writing credentials by hand in an IDE.

### 2. `VerifiableCredential` type definition - `type`

Based on my read of the spec: https://www.w3.org/TR/vc-data-model/#types

it appears that `type` is a required property for a `VerifiableCredential`:
<img width="824" alt="Screenshot 2023-06-14 at 9 55 33 AM" src="https://github.com/TBD54566975/web5-js/assets/134693/37ca6509-d42b-47f7-8237-c1b6964bb486">

and that it must be an array of strings for a VerifiableCredential.

If that is accurate, then we should change the type definition from:
https://github.com/TBD54566975/web5-js/blob/f78af053f6775b335bd58cd05d4fe25e76b16736/packages/credentials/src/types.ts#L13-L14
to:
```typescript
  type: string[];
```

This would make the code that modifies types easier to deal with by not having to contend with strings or arrays of strings and the potential to be undefined.

2023-06-15 20:22 UTC, nitro-neal commented
@frankhinek 
<img width="843" alt="image" src="https://github.com/TBD54566975/web5-js/assets/5314059/041ca13d-6f87-490e-9bcb-a1bb9dc30c50">

It seems to me context needs to just be an array of objects according to the spec. In practicality though we use it as an array of strings. In the ssi-sdk we just have a new string array:

contexts := []string{VerifiableCredentialsLinkedDataContext}

2023-06-16 19:43 UTC, nitro-neal commented
<img width="507" alt="image" src="https://github.com/TBD54566975/web5-js/assets/5314059/234677bc-36bb-4650-9bb5-c6832421bdd0">

Updating based on comments

2023-08-04 20:17 UTC, mistermoe commented
@nitro-neal should we close this in favor of #148 ?

2023-08-04 22:04 UTC, closed without merging