Updated README.md to improve import statements for crypto polyfills.
TBD54566975/web5-js pull request #211
Opened 2023-09-08 05:59 UTC by andorsk

Added some missing steps in ReactNative crypto.getRandomValues polyfill and sha512.

2023-09-12 18:57 UTC, frankhinek commented
Since `@noble/ed25519` and `@noble/secp256k1` are not dependencies of any packages in the polyrepo, ideally this could be done using the existing `@noble/curves` dependency.

@andorsk are you able to test and confirm this works in a React Native project?

```typescript
import { ed25519 } from '@noble/curves/ed25519';
import { secp256k1 } from '@noble/curves/secp256k1';
```

2023-09-12 18:57 UTC, frankhinek requested changes
Since `@noble/ed25519` and `@noble/secp256k1` are not dependencies of any packages in the polyrepo, ideally this could be done using the existing `@noble/curves` dependency.

@andorsk are you able to test and confirm this works in a React Native project?

```typescript
import { ed25519 } from '@noble/curves/ed25519';
import { secp256k1 } from '@noble/curves/secp256k1';
```

2023-11-03 13:28 UTC, frankhinek commented
> Since `@noble/ed25519` and `@noble/secp256k1` are not dependencies of any packages in the polyrepo, ideally this could be done using the existing `@noble/curves` dependency.
> 
> @andorsk are you able to test and confirm this works in a React Native project?
> 
> ```ts
> import { ed25519 } from '@noble/curves/ed25519';
> import { secp256k1 } from '@noble/curves/secp256k1';
> ```

@andorsk did you ever get time to test this?
@shamilovtim perhaps something you can validate?

My guess is that the issue stems from `dwn-sdk-js` using the `@noble/ed25519` and `@noble/secp256k1` libs directly since it doesn't yet import from `@web5/crypto`.

2023-11-03 15:07 UTC, andorsk commented
> > Since `@noble/ed25519` and `@noble/secp256k1` are not dependencies of any packages in the polyrepo, ideally this could be done using the existing `@noble/curves` dependency.
> > @andorsk are you able to test and confirm this works in a React Native project?
> > ```ts
> > import { ed25519 } from '@noble/curves/ed25519';
> > import { secp256k1 } from '@noble/curves/secp256k1';
> > ```
> 
> @andorsk did you ever get time to test this? @shamilovtim perhaps something you can validate?
> 
> My guess is that the issue stems from `dwn-sdk-js` using the `@noble/ed25519` and `@noble/secp256k1` libs directly since it doesn't yet import from `@web5/crypto`.

@frankhinek thanks for the comment. I have not been able to get back to this yet. The point of the additional imports was because the RN polyfills requiring access to `ed` and `secp` namespace according to the documentation. This may be out of date with the most current method, or it's possible the RN documentation has updated since this was a problem where there's no longer a conflict.

2023-11-03 16:53 UTC, shamilovtim requested changes
I would say since we're asking the community to use our packages:
https://github.com/TBD54566975/web5-react-native-polyfills
https://github.com/TBD54566975/web5-react-native-metro-config

We should update the README to reflect the installation instructions of those and tweak the current recommended install for RN

2023-11-03 16:53 UTC, shamilovtim commented
This can probably get closed and I'll get a separate PR with install steps going

2023-11-03 19:25 UTC, frankhinek commented
> This can probably get closed and I'll get a separate PR with install steps going

Ok, will do.  Thanks.

2023-11-03 19:25 UTC, closed without merging