Leordev/tbdocs api
TBD54566975/web5-js pull request #251
Opened 2023-10-31 14:28 UTC by leordev

- Installs `tbdocs` on `@web5/api`, which will start to bring up doc errors on PRs (powered by api-extractor)
- These errors are non blocking, you can feel free to ignore them if you want to, although not encouraged
- Since we aligned on this, I'm helping to fix the initial warnings pointed by tbdocs by fixing and adding missing docs (just a first pass, but please review my docs to see if it makes sense!)

(still a draft: wip fixing remaining warnings)

Fix #250

2023-10-31 17:30 UTC, leordev commented
> **TBDocs Report**
> 
> 🛑 Errors: 0 ⚠️ Warnings: 23

The above warnings will be fixed at the tbdocs level repo (hence could be ignored)

- The `abstract-level` compilations errors should be suppressed
- The missing documentation attributes are all from private properties that will be fixed with [this api-extractor PR](https://github.com/microsoft/rushstack/pull/4392) (I just need to test their changes and make sure it worked!)

2023-11-03 10:13 UTC, frankhinek requested changes
@leordev Thanks for getting this work started and contributing all of the much needed comments! 😄

2023-11-03 10:13 UTC, frankhinek commented on packages/api/src/record.ts
> +   * If the record data is null, it attempts to fetch the data from the DWN.
```suggestion
   * If the record data is not available, it attempts to fetch the data from the DWN.
```

2023-11-03 10:13 UTC, frankhinek commented on packages/api/src/did-api.ts
> + * for interacting with DIDs.
```suggestion
 * The DID API is used to create and resolve DIDs.
```

2023-11-03 10:13 UTC, frankhinek commented on packages/api/src/dwn-api.ts
> +   * Records manager, used to read, write, query and delete records
```suggestion
   * API to to interact with DWN records (e.g., `dwn.records.create()`).
```

2023-11-03 10:13 UTC, frankhinek commented on packages/api/src/dwn-api.ts
> +   * Retrieves the protocols manager, used to configure and query them
```suggestion
   * API to to interact with DWN protocols (e.g., `dwn.protocols.configure()`).
```

2023-11-03 10:15 UTC, frankhinek commented
@leordev Can you also rebase on main to clear the `security-audit` check failure?   The `package-lock.json` in `main` already has the patched version of `browserify-sign` updated.  Thanks.

2023-11-03 13:09 UTC, leordev commented
Thank you @frankhinek ! Just rebased and implemented the suggestions. 

Did you check if all the interfaces that I tagged as `@beta` but should already be in a stable enough state to be considered `@public`? 

If all of them should be `@beta`, feel free to go ahead and merge!

2023-11-03 13:12 UTC, frankhinek commented on packages/api/src/index.ts
> +export { utils };
@leordev Is this limitation with `api-extractor` something that is planned to be resolved?  Seems unfortunate that we have to modify the source code to satisfy `api-extractor` being unable to understand valid ES2020 syntax.

2023-11-03 13:14 UTC, frankhinek commented
> Thank you @frankhinek ! Just rebased and implemented the suggestions.

Thanks! 👍 
 
> Did you check if all the interfaces that I tagged as `@beta` but should already be in a stable enough state to be considered `@public`?
> 
> If all of them should be `@beta`, feel free to go ahead and merge!

I think `@beta` is fine for now.  We've got some changes upcoming to re-align the Web5 SDKs implemented in TS, Kotlin, and Swift/Rust so that might introduce changes.

2023-11-03 13:19 UTC, frankhinek approved these changes
LGTM! 🚀 Let's ship it!

2023-11-03 13:19 UTC, merged