Rename sdk-development -> web5-spec
TBD54566975/web5-js pull request #384
Opened 2024-01-22 19:55 UTC by leordev

2024-01-22 20:04 UTC, diehuxx approved these changes

2024-01-22 20:41 UTC, nitro-neal reviewed
so instead of web5-spec, the runner will be hosted here - 
https://github.com/TBD54566975/sdk-report-runner

2024-01-22 20:43 UTC, nitro-neal commented on .github/workflows/tests-ci.yml
> +          repositories: web5-spec
```suggestion
          repositories: sdk-report-runner
```

2024-01-22 20:44 UTC, nitro-neal commented on .github/workflows/tests-ci.yml
> +      - name: Trigger web5-spec report build
```suggestion
      - name: Trigger sdk-report-runner report build
```

2024-01-22 20:44 UTC, nitro-neal commented on .github/workflows/tests-ci.yml
> +          https://api.github.com/repos/TBD54566975/web5-spec/actions/workflows/build-report.yaml/dispatches
```suggestion
          https://api.github.com/repos/TBD54566975/sdk-report-runner/actions/workflows/build-report.yaml/dispatches
```

2024-01-22 20:45 UTC, frankhinek commented
In last week's Web5 Spec call, it was agreed that `sdk-development` would be renamed to `web5-spec` and the report generator / runner would be moved to its own repo.  I believe that work is still in progress but will need to be completed and then this PR updated to point to the new repo.

2024-01-22 20:45 UTC, nitro-neal approved these changes
update to sdk-report-runner and yea should be good to go, 

The code at sdk-report-runner may not be ready and an action may fail, but should be up and running soon

2024-01-22 20:49 UTC, frankhinek commented
@finn-tbd IIRC you requested responsibility to migrate the report runner over to the new repo.

What's your ETA?  If its not that far out we could hold off on approving this PR until the new `sdk-report-runner` repo is ready.

2024-01-22 20:50 UTC, frankhinek requested changes
In last week's Web5 Spec call, it was agreed that `sdk-development` would be renamed to `web5-spec` and the report generator / runner would be moved to its own repo.  I believe that work is still in progress but will need to be completed and then this PR updated to point to the new repo.

2024-01-22 21:15 UTC, finn-tbd commented
That was waiting on https://github.com/TBD54566975/web5-spec/pull/99, which just merged. I believe @nitro-neal is going to handle the rename now as i'm getting pulled into did:dht work

2024-01-23 01:18 UTC, nitro-neal approved these changes

2024-01-23 01:20 UTC, nitro-neal approved these changes

2024-01-25 00:55 UTC, leordev commented
@frankhinek the changes were addressed, can you please review it again? If it looks good for you, please go ahead and merge!

2024-01-25 17:28 UTC, frankhinek approved these changes

2024-01-25 17:29 UTC, merged